---
node_domain_role: backend
node_hostname: yii-bak
ansible_host: "{{ node_hostname }}.{{ platform_magicdns_suffix }}"

backend_bootstrap_host: "{{ platform_zones.bak.vm_ipv4_address }}"
backend_bootstrap_proxyjump: "neo@{{ hostvars['yii-dom0'].ansible_host | default('yii-dom0') }}"
backend_bootstrap_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/github-klokast-codex"
backend_bootstrap_known_hosts_file: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts_klokast_bootstrap"
