---
debian_vm_admin_user_name: "{{ vm_admin_user_name | default('neo') }}"
debian_vm_admin_authorized_key_file: "{{ vm_admin_authorized_key_file }}"
debian_vm_lock_root_password: true
debian_vm_manage_sshd: true
debian_vm_base_packages:
  - acl
  - bash
  - ca-certificates
  - curl
  - dbus
  - dbus-user-session
  - gnupg
  - iproute2
  - nftables
  - openssh-server
  - python3
  - sudo
  - systemd-sysv
debian_vm_local_users:
  - name: "{{ debian_vm_admin_user_name }}"
    shell: /bin/bash
    groups:
      - sudo
