---
debian_app_vm_release: "{{ platform_app_vm_guest_spec.debian_release | default('trixie') }}"
debian_app_vm_mirror: "{{ platform_app_vm_guest_spec.debian_mirror | default('http://deb.debian.org/debian') }}"
debian_app_vm_image: "{{ platform_app_vm_guest_spec.debian_image | default({}) }}"
debian_app_vm_architecture: "{{ debian_app_vm_image.architecture | default('amd64') }}"
debian_app_vm_target_lv_path: "{{ platform_app_vm_guest_spec.installed.required_lvs | first }}"
debian_app_vm_target_lv_size: "{{ platform_app_vm_guest_spec.lv_size | default('50G') }}"
debian_app_vm_mount_path: "/tmp/{{ platform_app_vm_guest_spec.guest_name }}-root"
debian_app_vm_work_dir: "{{ dom0_data_mount_path | default('/mnt/dom0_data') }}/tmp/klokast/debian-app-vm-images/{{ platform_app_vm_guest_spec.guest_name }}"
debian_app_vm_manifest_path: "{{ debian_app_vm_work_dir }}/manifest.json"
debian_app_vm_root_img_gz_path: "{{ debian_app_vm_work_dir }}/root.img.gz"
debian_app_vm_builder_artifact_host: "{{ platform_zones.bak.vm_ipv4_address }}"
debian_app_vm_builder_artifact_port: "{{ debian_app_vm_image.artifact_port | default(18082) }}"
debian_app_vm_artifact_base_url: "http://{{ debian_app_vm_builder_artifact_host }}:{{ debian_app_vm_builder_artifact_port }}/{{ platform_app_vm_guest_spec.guest_name }}"
debian_app_vm_hostname: "{{ hostvars[platform_app_vm_inventory_host].node_hostname }}"
debian_app_vm_bootstrap_host: "{{ hostvars[platform_app_vm_inventory_host].vm_bootstrap_host }}"
debian_app_vm_bootstrap_known_hosts_file: "{{ hostvars[platform_app_vm_inventory_host].vm_bootstrap_known_hosts_file }}"
debian_app_vm_rootfs_build_id: "{{ debian_app_vm_image.build_id | default('') }}"
debian_app_vm_rebuild: false
