worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8443;
        server_name _;

        location = /status.php {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://192.168.100.10:8080/status.php;
        }

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://192.168.100.10:8080;
        }
    }
}
