worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    upstream php-handler {
        server 127.0.0.1:9000;
    }

    server {
        listen 8080;
        server_name _;
        root /var/www/html;

        client_max_body_size 0;
        fastcgi_buffers 64 4K;

        location = /status.php {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root/status.php;
            fastcgi_pass php-handler;
        }

        location / {
            rewrite ^ /index.php$request_uri;
        }

        location ~ \.php(?:$|/) {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass php-handler;
        }
    }
}
